In [1]:
import numpy as np

print(np.exp(2))
print(np.log(np.e))
print(np.sin(np.pi))
print(np.sqrt(3))

7.38905609893065
1.0
1.2246467991473532e-16
1.7320508075688772


In [12]:
a = np.array([2,3,5,7,8])
print(a[2])
print(a[1:3]) # インデックス1から3の手前まで
print(a[2:-1])# インデックス2から末尾1まで

b = np.arange(5)
print(b)

c = np.arange(1, 3, 0.2)
print(c)

print(a.dtype)
print(c.dtype)

d = np.array([1,2,3], dtype=np.float64)
print(d)
print(d.dtype)

e = np.arange(5.)
print(e)
print(e.dtype)

5
[3 5]
[5 7]
[0 1 2 3 4]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]
int64
float64
[1. 2. 3.]
float64
[0. 1. 2. 3. 4.]
float64


In [18]:
a = np.array([[2,3,4],[5,6,7]], dtype=np.float64)
print(a)
print(a[0,1])
print(a[:,1])
print(a[1,:])
print(a[0,2:])
print(a[0,:2])

v = np.array([2.,3.,4.])
c = np.array([[1., 2.], [3., 4.]])

[[2. 3. 4.]
 [5. 6. 7.]]
3.0
[3. 6.]
[5. 6. 7.]
[4.]
[2. 3.]


In [26]:
a = np.arange(15.).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim) # => 2(次元配列)
print(a.size)

b = np.arange(4.)
print(b.shape)
print(b.ndim)
print(b.size)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
(3, 5)
2
15
(4,)
1
4


In [31]:
a = np.arange(16.)
c = a.reshape(4, -1) # 行数=4, 列数は自動(-1)
print(c)
print(c.ravel())
print(c.reshape(-1))

b = np.arange(4.)
print(b.reshape(-1,1))
print(b[:, np.newaxis])
print(b[:, None])

print(b.reshape(1,-1))
print(b[np.newaxis, :]) # np.newaxisはNoneのエイリアス

# 1次元配列と2次元配列は別物として扱われる

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[[0.]
 [1.]
 [2.]
 [3.]]
[[0.]
 [1.]
 [2.]
 [3.]]
[[0.]
 [1.]
 [2.]
 [3.]]
[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]]


In [37]:
a = np.zeros((3,4))
print(a)

b = np.ones((2,2))
print(b)

c = np.empty((2,5))
print(c)

d = np.linspace(0, 1, 10) # 返ってくるサイズは第3引数の個数分
print(d)
print(d.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.         0.11111111 0.22222222 0.33333333 0.44444444]
 [0.55555556 0.66666667 0.77777778 0.88888889 1.        ]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
10


In [45]:
a = np.arange(6).reshape(2,3)
print(a)
b = np.arange(6,12).reshape(2,3)
print(b)

print(np.r_[a,b]) # row
print(np.c_[a,b]) # column

c = np.arange(3) # 1次元ベクトルは縦ベクトルとみなされる
d = np.arange(3,6)
print(c)
print(d)

print(np.r_[c,d]) # 転置したものとして考える
print(np.c_[c,d]) # 列数2の行列

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[0 1 2]
[3 4 5]
[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]
